
services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: 8012328773:AAF4aVcR04HDEG7BWeVZ2jkjkT0GRy-yieM
        value: your_bot_token_here
      - key: ADMIN_CHAT_ID
        value: your_admin_id_here
